<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="INMUVADP014584" failures="1" tests="1" name="Runner.FailedRun" time="33.200" errors="0" timestamp="2022-08-04T09:49:27 IST" skipped="0">
  <testcase classname="Runner.FailedRun" name="runScenario" time="33.200">
    <failure type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError
at org.junit.Assert.fail(Assert.java:86)
at org.junit.Assert.assertTrue(Assert.java:41)
at org.junit.Assert.assertTrue(Assert.java:52)
at stepdefinitions.ULS_UnderWriterOffSetControl.verify_system_should_not_allow_user_to_save_the_record(ULS_UnderWriterOffSetControl.java:416)
at âœ½.verify system should not allow user to save the record(file:///C:/Users/inindc00076/git/KULS_Anandh/AzentioULSFramework_Anandh/src/test/java/features/ULS_UnderWriterOffSetControl.feature:241)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <system-out/>
</testsuite> <!-- Runner.FailedRun -->
